
import React from 'react';
import Head from 'next/head';
const axios = require('axios');
import { useRouter } from 'next/router';
import styles from '../../styles/Home.module.css';

export default function User({user}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h3>{user.name}</h3>
        <p>{user.email}</p>

      </main>
    </div>
  )
}

export async function getServerSideProps({query}) {
  const { userid } = query;

  const response = await axios.get('https://jsonplaceholder.typicode.com/users/' + userid);
  const user = response.data;

  return {
    props: {
      user
    }
  }
}
