import Head from 'next/head';
import Link from 'next/link';
const axios = require('axios');
import styles from '../../styles/Home.module.css';
// import Users from '../../json-data/Users.json';

export default function UserList({ users }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
            {users.map(user => {
                return <li key={user.id}>
                    <h3>
                        <Link href={"/users/[userid]"} as={"/users/" + user.id}>
                            <a>{user.name}</a>
                        </Link>
                    </h3>
                    <p>{user.email}</p>
                </li>
            })}
        </ul>

      </main>
    </div>
  )
}

// export async function getStaticProps() {
//   const response = await axios.get('https://jsonplaceholder.typicode.com/users');
//   const users = response.data;

//   return {
//     props: {
//       users
//     }
//   }
// }

export async function getServerSideProps() {
  const response = await axios.get('https://jsonplaceholder.typicode.com/users');
  const users = response.data;

  return {
    props: {
      users
    }
  }
}
